introducción a Numpy en python.

In [19]:
import numpy as np

In [46]:
def crearArray(fila,columna):
    array = np.random.random((fila,columna))
    return array

In [20]:
#import numpy as np
array_1d = np.array([1,5,4])
print(array_1d)

[1 5 4]


In [21]:
array_2d = np.array([(1,2,3),(4,3,2)])
print(array_2d)

[[1 2 3]
 [4 3 2]]


In [22]:
array_3d = np.array([[(1,2,3),(3,6,5)],[(3,3,3),(8,0,1)],[(2,3,5),(1,4,2)]],dtype = float)
print(array_3d)

[[[1. 2. 3.]
  [3. 6. 5.]]

 [[3. 3. 3.]
  [8. 0. 1.]]

 [[2. 3. 5.]
  [1. 4. 2.]]]


Creando arreglos 


In [23]:
#de ceros con 3 filas y 4 columnas
array_ceros = np.zeros((3,4))
print(array_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
#de unos con 2 dimensiones 4 filas y 5 columans
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [26]:
#intervalos y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [27]:
#intervalos y dimensiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [28]:
#valor dado
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [29]:
#matriz identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#valores aleatorios entre 0 y 1
np.random.random((5,5))

array([[0.3766774 , 0.3713351 , 0.28620578, 0.42718171, 0.27167255],
       [0.8227329 , 0.24985177, 0.92616801, 0.51959048, 0.5593438 ],
       [0.62188415, 0.60196861, 0.51762554, 0.79001531, 0.35402655],
       [0.51152411, 0.45307267, 0.95681884, 0.44618932, 0.36660552],
       [0.72475178, 0.63718879, 0.80204736, 0.567234  , 0.10353811]])

In [31]:
#vacío de 4 filas y 3 colums
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# primera forma para grabar y cargar arreglos

In [32]:
#grabar
np.save('mi_array', np.random.random((3,3)))

In [33]:
#cargar 
mi_array = np.load('mi_array.npy')
mi_array

array([[0.98611938, 0.54503227, 0.48270371],
       [0.18824707, 0.30783743, 0.46522124],
       [0.25191478, 0.02548147, 0.69091553]])

In [34]:
np.save('mi_array_3d', array_3d)


In [35]:
mi_array3 = np.load('mi_array_3d.npy')
mi_array3

array([[[1., 2., 3.],
        [3., 6., 5.]],

       [[3., 3., 3.],
        [8., 0., 1.]],

       [[2., 3., 5.],
        [1., 4., 2.]]])

# propiedades y caracteristicas de los arrays.

In [36]:
array_3d

array([[[1., 2., 3.],
        [3., 6., 5.]],

       [[3., 3., 3.],
        [8., 0., 1.]],

       [[2., 3., 5.],
        [1., 4., 2.]]])

In [37]:
#dimensiones o forma 
array_3d.shape

(3, 2, 3)

In [38]:
#longitud 
len(array_3d)

3

In [39]:
#num de dimensiones
array_3d.ndim

3

In [40]:
#número de elementos
array_3d.size


18

In [41]:
#tipos de datos
array_3d.dtype

dtype('float64')

In [42]:
array_3d.dtype.name

'float64'

In [43]:
#convertir de un tipo a otro 
array_3d.astype(int)

array([[[1, 2, 3],
        [3, 6, 5]],

       [[3, 3, 3],
        [8, 0, 1]],

       [[2, 3, 5],
        [1, 4, 2]]])

In [45]:
#ayuda 
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Estadísticos básicos y otras funcvcionrs

In [47]:
array1 = crearArray(5,5)
print(array1)

[[0.52968931 0.65980798 0.23080214 0.72064268 0.81098156]
 [0.61250859 0.6309765  0.89036011 0.05278364 0.46941268]
 [0.78342161 0.69882795 0.17754727 0.72950087 0.74507943]
 [0.57864147 0.2687443  0.33878939 0.87190729 0.0153799 ]
 [0.72573489 0.86578756 0.63022818 0.21418938 0.39254858]]


In [54]:
#suma del valor del array anterios
sumaTotal = array1.sum()
print(sumaTotal)

13.644293260202309


In [56]:
valorMinimo = array1.min()
print(valorMinimo)

0.015379902574772397


In [57]:
valorMaximo = array1.max()
print(valorMaximo)

0.8903601064190587


In [58]:
#maximo por filas
array1.max(axis=0)

array([0.78342161, 0.86578756, 0.89036011, 0.87190729, 0.81098156])

In [59]:
#maximo por columnas
array1.max(axis=1)

array([0.81098156, 0.89036011, 0.78342161, 0.87190729, 0.86578756])

In [60]:
#suma acumulada
array1.cumsum(axis=1)

array([[0.52968931, 1.18949729, 1.42029943, 2.1409421 , 2.95192366],
       [0.61250859, 1.2434851 , 2.1338452 , 2.18662885, 2.65604152],
       [0.78342161, 1.48224956, 1.65979683, 2.3892977 , 3.13437713],
       [0.57864147, 0.84738577, 1.18617516, 2.05808246, 2.07346236],
       [0.72573489, 1.59152245, 2.22175063, 2.43594001, 2.82848859]])

In [62]:
#media
np.mean(array1)

0.5457717304080923

In [64]:
#mediana
np.median(array1)

0.6302281816725296

In [65]:
#correlacion
np.corrcoef(array1)

array([[ 1.        , -0.73216691,  0.86094757, -0.07273012, -0.40737086],
       [-0.73216691,  1.        , -0.63577232, -0.55676103,  0.7618852 ],
       [ 0.86094757, -0.63577232,  1.        ,  0.14895174, -0.14698686],
       [-0.07273012, -0.55676103,  0.14895174,  1.        , -0.33556042],
       [-0.40737086,  0.7618852 , -0.14698686, -0.33556042,  1.        ]])

In [66]:
#desviacion
np.std(array1)

0.2580992565249016

# copiando arrays

In [72]:
arrayA = np.random.randint(21, size = (4,4))
arrayA

array([[ 7,  2, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])

In [73]:
#crear una imagen de un array
array_cop = arrayA.view()
array_cop

array([[ 7,  2, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])

In [74]:
np.array_equal(arrayA,array_cop)

True

In [75]:
#modificar un valor de la copia
array_cop[0,1]=99

In [76]:
array_cop

array([[ 7, 99, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])

In [77]:
arrayA

array([[ 7, 99, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])

In [78]:
#creando copia independiente
array_cop2 = np.copy(arrayA)
array_cop2

array([[ 7, 99, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])

In [79]:
array_cop2[2,3] = 77
array_cop2

array([[ 7, 99, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2, 77],
       [15, 14,  1, 10]])

In [80]:
arrayA

array([[ 7, 99, 14, 13],
       [ 5,  4,  9, 18],
       [ 3,  4,  2,  1],
       [15, 14,  1, 10]])